### PR TITLE
feat: playwright tests

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

Adds basic e2e test coverage to the plugin. 

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [x] New or updated tests are included

### CODE REVIEW

**Comment by hirasso** [comment]
@daun how exactly do I install the browsers for playwright? Is the action [`test:e2e:install`](https://github.com/swup/swup/blob/master/package.json#L42) in swup actually being exectued from somewhere? 

https://github.com/swup/fragment-plugin/actions/runs/6852523927/job/18631255071?pr=64#step:7:12

**Comment by daun** [comment]
@hirasso I don't think it's being executed. The core's rather complicated GitHub action does that on its own. With the much simpler action files for the plugin, you could run the npm script from there.

**Comment by hirasso** [comment]
TIL [caching playwright](https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/) isn't necessary speeding up actions.

[Without cache](https://github.com/swup/fragment-plugin/actions/runs/6860644592/job/18654833038): 2m20s
[With cache](https://github.com/swup/fragment-plugin/actions/runs/6860670933/job/18654906963): 2m 57s

**Comment by hirasso** [comment]
@daun do you understand what's happening here? 

https://github.com/swup/fragment-plugin/actions/runs/6860973311/job/18655736640?pr=64#step:8:10

> Error: Report file results.json not found. Make sure Playwright is configured to generate a JSON report.

If I understand the config correctly, it should spit out the `results.json` at the root when in CI:

```js
reporter: process.env.CI
	? [['dot'], ['github'], ['json', { outputFile: '../../report.json' }]]
	: [['list'], ['html', { outputFolder: '../reports/html', open: 'on-failure' }]],
```

Although swup's playwright config doesn't even report JSON at all when in CI: https://github.com/swup/swup/blob/1cd87ea335b95b9b8caee602634974f5011d2cc7/tests/config/playwright.config.ts#L32-L40

**Comment by hirasso** [comment]
It's not THAT important I'd say, I could totally live without the reporter in the PR tbh :)

**Comment by daun** [comment]
@hirasso It's currently `report.json` vs. `results.json` 🤠 Matching both should fix it hopefully.

**Comment by hirasso** [comment]
Haha true 😆 so many trees 🌲🌳🌴🏝️

**Comment by hirasso** [comment]
OMG it's working! 🤯🥳 

...ready for review 🤪

**Comment by hirasso** [comment]
I guess the [playwright shield status](https://github.com/swup/fragment-plugin/tree/feat/playwright-tests) will appear when this is merged.

**Comment by hirasso** [comment]
I decided to use "vitest" and "playwright" instead of "unit" and "e2e" since the vitest tests aren't all real unit tests. The line is blurry.

**Comment by daun** [comment]
Makes sense! The reason I've used `functional` and `unit` was mostly to make it understandable for people who haven't used/heard of both tools, but that's probably not too many people anyway.

**Review by daun — APPROVED** [review]
Nice work 🥯

**Pull request merged**
