### PR TITLE
feat: modify rules on the fly

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

On large websites or in complex cases it could come in handy to be able to modify fragment rules on the fly. This PR is adding a few new API functions:

```js

/** Keep a reference to fragment plugin during instanciation */
const fragmentPlugin = new SwupFragmentPlugin({ rules });
new Swup({ plugins: [fragmentPlugin] });

/** Higher-Level methods: */

/** Prepend a fragment rule */
fragmentPlugin.prependRule(rule);

/** Append a fragment rule */
fragmentPlugin.appendRule(rule);

/** Lower-Level methods: */

/** Get a structured clone of the current rules */
fragmentPlugin.getRules();

/** Update the fragment rules */
fragmentPlugin.setRules(rules: Rule[]);
```

**Questions**

Is [structuredClone](https://caniuse.com/?search=structuredClone) ready to be used?

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [x] New or updated tests are included
- [ ] The documentation was updated as required in #59

### CODE REVIEW

**Comment by hirasso** [comment]
@daun ready for review :)

**Comment by daun** [comment]
API looks great! Is there an alternative for `structuredClone` that has been supported for a little longer? When creating sites with a two-year browser support window, it will require a [polyfill](https://github.com/ungap/structured-clone) that adds a few kilobytes. Or maybe the plugin could check if `structuredClone` is supported and only use it if found, otherwise do a shallow copy?

**Comment by hirasso** [comment]
Hmm, right... I think I'll go with a detection for structuredClone and otherwise return a shallow copy, combined with a warning if `options.debug` is `true`

**Comment by hirasso** [comment]
...turns out cloning the rules by myself wasn't so hard, as it's structure is well known. `structuredClone` dependency is gone!

**Review by daun — APPROVED** [review]

**Pull request merged**
